version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: promo_app
        working_dir: /var/www/html/promo-api
        volumes:
            - .:/var/www/html/promo-api
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html/promo-api
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootPWD123
            MYSQL_DATABASE: promo_api
            MYSQL_USER: promo
            MYSQL_PASSWORD: promoPWD123
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"

volumes:
    db-data:
